### ISSUE TITLE
Error autentificando en myBus

### ISSUE THREAD

**Issue by hhkaos** [esri-es/mobilitylab-emtmadrid#2]
Al igual que en #1, no sé por qué no me funciona este ejemplo, uso las mismas credenciales que funcionan para [myBus.py](https://github.com/esri-es/mobilitylab-emtmadrid/blob/master/myBus.py) pero me responde esto:

``` bash
mobilitylab git:(master) ✗ python myBus.py
accesing to bus Id...8241
Traceback (most recent call last):
  File "myBus.py", line 41, in <module>
    response = urllib2.urlopen(urlbus + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 911, in http_error_401
    url, req, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 889, in http_error_auth_reqed
    return self.retry_http_basic_auth(host, req, realm)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 899, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by jgcasta** [comment]
Hola

He intentado iniciar sesión con mis credenciales directamente en el navegador sobre https://mybus.emtmadrid.es:8073/rests y provoca el mismo error. ¿Puede ser un problema de las credenciales que no permitan acceder de esta manera?

**Comment by hhkaos** [comment]
Estoy probando con esto:

```
idCliente: EMT.SERVICIOS.OPENBUS
passkey: A2C983E5-5BA3-41F3-B47C-428F467041DC
```

Sacado de [este PDF](http://cordis.europa.eu/docs/projects/cnect/3/609043/080/deliverables/001-CosmosD732SmartEventsandprotocolsforsmartpublictransportImplementationandExperimentationAres20153668655.pdf) encontrado en Google y con esas credenciales sí que funciona ^_^''

**Comment by hhkaos** [comment]
De momento (hasta que averigüe qué credenciales deberían ser las que se introducen ahí...), con [este commit](https://github.com/esri-es/mobilitylab-emtmadrid/commit/15b2c9316b9f19783b90e136d9ee03738b275fe6) ya podemos ver lo que devuelve :)

**Comment by jgcasta** [comment]
Bueno debe ser entonces de credenciales y que no sean válidas para ese servicio porque con las otras si que va
